"""Auto-grant epithets (master.mdb honor_data) whose real condition is
actually met -- the "apply" half of tools/extract_honor_data.py's catalogue
(data/training_ref/honor_data.json, generated by that tool; NOT re-derived
from master.mdb here, same "extract once, load as data" split cards.json/
uma_data.json already use for training_formula.py).

Real epithets have NO claim step (unlike missions.py's mission/receive) --
the Epithet screen just shows whatever you've earned, the moment you earn
it. So this recomputes+grants on every honor/index load (see user_profile.
handle_honor_index) rather than needing a receive-style endpoint: cheap
(a few hundred dict lookups, no DB writes unless something NEWLY qualifies)
and can never drift, since nothing is cached across calls except the
already-earned set honor_state already owns.

Only rows the catalogue's own condition.kind resolved to a COMPLETE, real
state hook are evaluated (see _EVALUATORS below) -- every row still
carrying needs_unbuilt_system (136) or admittedly incomplete (11:
aptitude_all_s's undecided numeric grade coding, currency_threshold's
undecided state key, main_story_act_chapter's un-resolved main_story_data
id range) is silently skipped, same "don't guess into live gameplay" rule
as everywhere else in this codebase. That's 402 of 549 honors (100101
"Rookie Trainer" needs no check at all -- seeded directly by user_profile.
_honor_state).

Reuses missions.py's own real-state helpers wherever the SAME achievement
already has a mission counterpart (_genuine_roster, _love_rank_level,
_program_race_row, _won_race_ids, _trophy_instance_ids, _finale_program_ids,
_race_ids_by_name) rather than re-deriving them -- guarantees an epithet and
its mission twin (e.g. AllTrophiesForChara/100056 and honor_id 101505's
"Special Week Completionist") can never quietly disagree.

CLAIM-GATED HONORS ARE EXCLUDED (2026-08-19, user-caught): mission_data's
item_category=55 IS "grant this honor_id as the reward" (stories.py's
_grant_reward, _HONOR_CATEGORY -- GameDefine.ItemCategory.HONOR) -- 456 of
honor_data's 549 rows are the reward on at least one real mission row. For
those, the mission's own condition IS the honor's real unlock gate, and the
real client only grants it when the player actually visits mission/receive
and claims it -- honor_data's own condition_type being 0 for nearly all of
them (see extract_honor_data.py's docstring) means the description text
this module used to auto-check was never a SEPARATE trigger, just the
tooltip explaining what the linked mission requires. Auto-granting off that
text (this module's first version) bypassed the claim step entirely --
players got the title before ever seeing/claiming the mission that's
supposed to award it. _mission_reward_honor_ids() filters those 456 back
out of the catalogue below, leaving only the 93 honors NO mission ever
grants (100101's default plus condition_type 1-5's event/Champions/exam
family, all still unbuilt-system-gated) as auto-grant candidates -- which
in practice, as of this catalogue, is none: every row this module can
currently EVALUATE (kind in _EVALUATORS) turned out to also be a mission
reward. That's correct, not a bug -- it means every title this server can
currently grant a real condition for is already reachable the intended way,
through missions.py. This module stays as the auto-grant path for whatever
becomes resolvable later (or gets a mission-independent honor_data
condition_type in a future master.mdb) rather than being ripped out."""

from __future__ import annotations

import json
from pathlib import Path

from .. import master_data
from . import collection, missions, single_mode_team, stories, team_stadium

_CATALOGUE_PATH = (Path(__file__).resolve().parents[3]
                   / "data" / "training_ref" / "honor_data.json")

_catalogue_cache: list | None = None
_mission_reward_honor_ids_cache: frozenset | None = None


def _mission_reward_honor_ids() -> frozenset:
    """Every honor_id ANY real mission_data row grants (item_category=55,
    stories._HONOR_CATEGORY) -- these are claim-gated, never auto-granted
    here. Cached (static master data)."""
    global _mission_reward_honor_ids_cache
    if _mission_reward_honor_ids_cache is None:
        rows = master_data.query(
            "SELECT DISTINCT item_id FROM mission_data WHERE item_category=55")
        _mission_reward_honor_ids_cache = frozenset(r["item_id"] for r in rows)
    return _mission_reward_honor_ids_cache


def _catalogue() -> list:
    """The extracted honor_data.json, filtered to rows this module actually
    knows how to evaluate (kind in _EVALUATORS) AND that no mission already
    claim-gates (see the module docstring's CLAIM-GATED HONORS section) --
    cached for the process lifetime, same as every other static-master-data
    cache in this codebase. Missing file (extraction never run) just means
    no auto-grants, not a crash -- matches the file's own "documentation,
    not a hard dependency" relationship to the rest of the server
    established this session."""
    global _catalogue_cache
    if _catalogue_cache is None:
        try:
            with open(_CATALOGUE_PATH, encoding="utf-8") as f:
                data = json.load(f)
        except FileNotFoundError:
            data = []
        claim_gated = _mission_reward_honor_ids()
        _catalogue_cache = [d for d in data if d["condition"]["kind"] in _EVALUATORS
                            and d["honor_id"] not in claim_gated]
    return _catalogue_cache


# ---------------------------------------------------------------- helpers --
_G13_GRADES = (100, 200, 300)


def _grade_trophy_instance_ids(grade: int) -> frozenset:
    """Per-GRADE canonical trophy race_instance_ids (unlike missions.py's
    _trophy_instance_ids, which is all three combined) -- for
    all_trophies_by_grade (account-wide 'G1/G2/G3 Giant', distinct from
    all_trophies_for_chara's per-character combined-grade version)."""
    rows = master_data.query(
        "SELECT rt.race_instance_id AS inst FROM race_trophy rt "
        "JOIN race_instance ri ON ri.id = rt.race_instance_id "
        "JOIN race rc ON rc.id = ri.race_id WHERE rc.grade=?", (grade,))
    return frozenset(r["inst"] for r in rows)


_BIG_EIGHT_NAMES = ("Oka Sho", "Satsuki Sho", "Tenno Sho (Spring)", "Japanese Oaks",
                   "Tokyo Yushun (Japanese Derby)", "Kikuka Sho", "Tenno Sho (Autumn)",
                   "Arima Kinen")


class Context:
    """Everything the evaluators below read, fetched ONCE per honor/index
    call instead of once per honor (402 rows would otherwise mean 402
    redundant roster/collection refetches for the exact same viewer)."""

    def __init__(self, viewer_id, full_state: dict, owned_honor_count: int = 0):
        self.genuine = missions._genuine_roster(viewer_id)
        self.charas = full_state.get(collection.CHARA_LIST_KEY) or []
        self.cards = full_state.get(collection.CARD_LIST_KEY) or []
        self.support_cards = full_state.get(collection.SUPPORT_CARD_KEY) or []
        self.story_state = stories._story_state(full_state)
        crane_lifetime = full_state.get(single_mode_team.CRANE_LIFETIME_KEY) or {}
        self.crane_lifetime_plushies = crane_lifetime.get("plushie_count") or 0
        ts_state = full_state.get(team_stadium.TEAM_STADIUM_STATE_KEY) or {}
        self.team_best_point = ts_state.get("best_point") or 0
        self.owned_honor_count = owned_honor_count

    def won_race_grade_count(self, grade: int) -> int:
        total = 0
        for c in self.genuine:
            for pid in c.get("_won_program_ids") or ():
                row = missions._program_race_row(pid)
                if row and row["grade"] == grade:
                    total += 1
        return total

    def won_race_ids_at(self, race_ids) -> int:
        target = frozenset(race_ids)
        total = 0
        for c in self.genuine:
            for pid in c.get("_won_program_ids") or ():
                row = missions._program_race_row(pid)
                if row and row["race_id"] in target:
                    total += 1
        return total

    def distinct_songs_performed(self) -> set:
        out = set()
        for c in self.genuine:
            for l in c.get("grand_live_lives_done") or ():
                out.update(l.get("song_ids") or ())
        return out


# --------------------------------------------------------------- dispatch --
# Each entry: kind -> fn(ctx, condition) -> bool. condition is the row's own
# already-resolved "condition" dict from honor_data.json (chara_id/
# threshold/etc.), so no re-parsing happens here, only real-state reads.
_EVALUATORS: dict = {}


def _evaluator(kind: str):
    def deco(fn):
        _EVALUATORS[kind] = fn
        return fn
    return deco


@_evaluator("chara_fan_threshold")
def _e_chara_fan_threshold(ctx: Context, cond: dict) -> bool:
    total = sum(c.get("fan") or 0 for c in ctx.charas if c.get("chara_id") == cond["chara_id"])
    return total >= cond["threshold"]


@_evaluator("chara_story_episode")
def _e_chara_story_episode(ctx: Context, cond: dict) -> bool:
    return cond["chara_story_data_id"] in (ctx.story_state.get("chara_cleared") or [])


@_evaluator("grade_win_count")
def _e_grade_win_count(ctx: Context, cond: dict) -> bool:
    return ctx.won_race_grade_count(cond["grade"]) >= cond["threshold"]


@_evaluator("all_trophies_by_grade")
def _e_all_trophies_by_grade(ctx: Context, cond: dict) -> bool:
    target = _grade_trophy_instance_ids(cond["grade"])
    if not target:
        return False
    won = set()
    for c in ctx.genuine:
        for pid in c.get("_won_program_ids") or ():
            row = missions._program_race_row(pid)
            if row and row["grade"] == cond["grade"]:
                won.add(row["inst"])
    return target <= won


@_evaluator("rank_achieved_count")
def _e_rank_achieved_count(ctx: Context, cond: dict) -> bool:
    n = sum(1 for c in ctx.genuine if (c.get("rank") or 0) >= cond["rank_id"])
    return n >= cond["threshold"]


@_evaluator("team_rank")
def _e_team_rank(ctx: Context, cond: dict) -> bool:
    return ctx.team_best_point >= cond["team_min_value"]


@_evaluator("venue_win_count")
def _e_venue_win_count(ctx: Context, cond: dict) -> bool:
    return ctx.won_race_ids_at(cond["race_ids"]) >= cond["threshold"]


@_evaluator("crane_session_plushies")
def _e_crane_session_plushies(ctx: Context, cond: dict) -> bool:
    return any((c.get("_crane_session_plushies") or 0) >= cond["threshold"] for c in ctx.genuine)


@_evaluator("crane_lifetime_plushies")
def _e_crane_lifetime_plushies(ctx: Context, cond: dict) -> bool:
    return ctx.crane_lifetime_plushies >= cond["threshold"]


@_evaluator("career_fan_threshold")
def _e_career_fan_threshold(ctx: Context, cond: dict) -> bool:
    return any((c.get("fans") or 0) >= cond["threshold"] for c in ctx.genuine)


@_evaluator("ura_finale_win")
def _e_ura_finale_win(ctx: Context, cond: dict) -> bool:
    finale_ids = missions._finale_program_ids()
    return any(finale_ids & set(c.get("_won_program_ids") or ()) for c in ctx.genuine)


@_evaluator("big_eight")
def _e_big_eight(ctx: Context, cond: dict) -> bool:
    targets = [missions._race_ids_by_name(n) for n in _BIG_EIGHT_NAMES]
    for c in ctx.genuine:
        won = missions._won_race_ids(c)
        if all(won & t for t in targets):
            return True
    return False


@_evaluator("add_trainees")
def _e_add_trainees(ctx: Context, cond: dict) -> bool:
    return len(ctx.genuine) >= cond["threshold"]


@_evaluator("support_card_kind_num")
def _e_support_card_kind_num(ctx: Context, cond: dict) -> bool:
    return len(ctx.support_cards) >= cond["threshold"]


@_evaluator("watch_unique_concerts")
def _e_watch_unique_concerts(ctx: Context, cond: dict) -> bool:
    return len(ctx.distinct_songs_performed()) >= cond["threshold"]


@_evaluator("unlock_star_count")
def _e_unlock_star_count(ctx: Context, cond: dict) -> bool:
    n = sum(1 for c in ctx.cards if (c.get("talent_level") or 1) >= cond["star"])
    return n >= cond["threshold"]


@_evaluator("all_trophies_for_chara")
def _e_all_trophies_for_chara(ctx: Context, cond: dict) -> bool:
    target = missions._trophy_instance_ids()
    if not target:
        return False
    won = set()
    for c in ctx.genuine:
        if missions._chara_id_for_card(c.get("card_id")) != cond["chara_id"]:
            continue
        for pid in c.get("_won_program_ids") or ():
            row = missions._program_race_row(pid)
            if row and row["grade"] in _G13_GRADES:
                won.add(row["inst"])
    return target <= won


@_evaluator("bond_level_threshold_count")
def _e_bond_level_threshold_count(ctx: Context, cond: dict) -> bool:
    n = sum(1 for c in ctx.charas
           if missions._love_rank_level(c.get("love_point") or 0) >= cond["bond_level"])
    return n >= cond["chara_count"]


@_evaluator("title_collector")
def _e_title_collector(ctx: Context, cond: dict) -> bool:
    return ctx.owned_honor_count >= cond["threshold"]


@_evaluator("view_distinct_stories")
def _e_view_distinct_stories(ctx: Context, cond: dict) -> bool:
    st = ctx.story_state
    total = (len(st.get("chara_cleared") or [])
            + len(st.get("main_cleared") or [])
            + len(st.get("story_event_cleared") or []))
    return total >= cond["threshold"]


@_evaluator("watch_song")
def _e_watch_song(ctx: Context, cond: dict) -> bool:
    live_id = cond["live_id"]
    for c in ctx.genuine:
        for l in c.get("grand_live_lives_done") or ():
            if live_id in (l.get("song_ids") or ()):
                return True
    return False


@_evaluator("skill_combo_owned")
def _e_skill_combo_owned(ctx: Context, cond: dict) -> bool:
    target = cond["skill_ids"]
    for c in ctx.genuine:
        owned = {s.get("skill_id") for s in c.get("skill_array") or ()}
        if all(sid in owned for sid in target):
            return True
    return False


@_evaluator("concert_all_great")
def _e_concert_all_great(ctx: Context, cond: dict) -> bool:
    for c in ctx.genuine:
        lives = c.get("grand_live_lives_done") or []
        if lives and all(l.get("result_state") == 2 for l in lives):
            return True
    return False


def newly_earned_honor_ids(viewer_id, full_state: dict, already_earned: set,
                           owned_honor_count: int) -> list:
    """Every honor_id in the catalogue that ISN'T already earned but whose
    real condition IS met right now. Caller (user_profile.grant_honor, one
    call per id) owns actually persisting them -- this only evaluates."""
    ctx = Context(viewer_id, full_state, owned_honor_count)
    out = []
    for row in _catalogue():
        hid = row["honor_id"]
        if str(hid) in already_earned:
            continue
        fn = _EVALUATORS.get(row["condition"]["kind"])
        if fn and fn(ctx, row["condition"]):
            out.append(hid)
    return out
